### ISSUE TITLE
Prettier v3.3.0: Error: Found "[" but: its sibling was not an indent Doc.: 

### ISSUE THREAD

**Issue by moltar** [electrovir/prettier-plugin-newline-arrays#35]
After upgrading prettier to v3.3.0, started getting this error:

```
Oops! Something went wrong! :(

ESLint: 8.57.0

Error: Found "[" but: its sibling was not an indent Doc.: 
    at /codebuild/output/src2521194580/src/actions-runner/_work/infra/infra/node_modules/.pnpm/prettier-plugin-multiline-arrays@3.0.4_prettier@3.3.0/node_modules/prettier-plugin-multiline-arrays/dist/printer/insert-new-lines.js:57:23
    at walkDoc (/codebuild/output/src2521194580/src/actions-runner/_work/infra/infra/node_modules/.pnpm/prettier-plugin-multiline-arrays@3.0.4_prettier@3.3.0/node_modules/prettier-plugin-multiline-arrays/dist/printer/child-docs.js:28:10)
    at /codebuild/output/src2521194580/src/actions-runner/_work/infra/infra/node_modules/.pnpm/prettier-plugin-multiline-arrays@3.0.4_prettier@3.3.0/node_modules/prettier-plugin-multiline-arrays/dist/printer/child-docs.js:41:20
    at Array.every (<anonymous>)
    at walkDoc (/codebuild/output/src2521194580/src/actions-runner/_work/infra/infra/node_modules/.pnpm/prettier-plugin-multiline-arrays@3.0.4_prettier@3.3.0/node_modules/prettier-plugin-multiline-arrays/dist/printer/child-docs.js:40:18)
    at walkDoc (/codebuild/output/src2521194580/src/actions-runner/_work/infra/infra/node_modules/.pnpm/prettier-plugin-multiline-arrays@3.0.4_prettier@3.3.0/node_modules/prettier-plugin-multiline-arrays/dist/printer/child-docs.js:51:16)
    at /codebuild/output/src2521194580/src/actions-runner/_work/infra/infra/node_modules/.pnpm/prettier-plugin-multiline-arrays@3.0.4_prettier@3.3.0/node_modules/prettier-plugin-multiline-arrays/dist/printer/child-docs.js:41:20
    at Array.every (<anonymous>)
    at walkDoc (/codebuild/output/src2521194580/src/actions-runner/_work/infra/infra/node_modules/.pnpm/prettier-plugin-multiline-arrays@3.0.4_prettier@3.3.0/node_modules/prettier-plugin-multiline-arrays/dist/printer/child-docs.js:40:18)
    at insertLinesIntoArray (/codebuild/output/src2521194580/src/actions-runner/_work/infra/infra/node_modules/.pnpm/prettier-plugin-multiline-arrays@3.0.4_prettier@3.3.0/node_modules/prettier-plugin-multiline-arrays/dist/printer/insert-new-lines.js:17:30)
```

**Comment by electrovir** [comment]
fixed: https://github.com/electrovir/prettier-plugin-multiline-arrays/issues/32#issuecomment-2145392810
